version: "3.9"
services:
    web:
        build: .
        ports:
            - "8000:80"
        environment:
            ASPNETCORE_ENVIRONMENT: Production
        restart: unless-stopped
        depends_on:
            - db
    db:
        image: "mcr.microsoft.com/mssql/server"
        environment:
            SA_PASSWORD: "Your_password123"
            ACCEPT_EULA: "Y"
        restart: unless-stopped
        volumes:
            - sql-data:/var/opt/mssql
    migrations:
        build:
            context: .
            dockerfile: migrations.Dockerfile
        environment:
            ASPNETCORE_ENVIRONMENT: Production
        depends_on:
            - web
            - db

volumes:
  sql-data: